# Generated by Django 5.1.3 on 2025-04-19 23:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_remove_diagnosis_diagnosis_result_and_more'),
        ('patient_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='patientform',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='patientform',
            old_name='notes',
            new_name='other_conditions',
        ),
        migrations.RemoveField(
            model_name='patientform',
            name='affected_area',
        ),
        migrations.RemoveField(
            model_name='patientform',
            name='condition_known',
        ),
        migrations.RemoveField(
            model_name='patientform',
            name='diagnosis_year',
        ),
        migrations.RemoveField(
            model_name='patientform',
            name='image',
        ),
        migrations.RemoveField(
            model_name='patientform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patientform',
            name='skin_condition',
        ),
        migrations.AddField(
            model_name='patientform',
            name='additional_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.AddField(
            model_name='patientform',
            name='affected_body_parts',
            field=models.CharField(choices=[('Face', 'Face'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Other', 'Other')], default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientform',
            name='condition_frequency',
            field=models.CharField(choices=[('Once', 'Once'), ('1-3 times', '1-3 times'), ('More than 3 times', 'More than 3 times')], default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientform',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='duration',
            field=models.CharField(choices=[('Less than 1 month', 'Less than 1 month'), ('1-6 months', '1-6 months'), ('More than 6 months', 'More than 6 months')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientform',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='diagnosis.patient'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_from_patient', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='diagnosis.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='patient_form.doctor')),
            ],
        ),
    ]
