# Generated by Django 5.1.3 on 2025-04-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_form', '0002_doctor_rename_dob_patientform_date_of_birth_and_more'),
    ]

    operations = [
    ]
