# Generated by Django 5.1.3 on 2025-04-22 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_form', '0003_auto_20250420_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientform',
            name='submitted_at',
        ),
    ]
