# Generated by Django 5.1.3 on 2025-03-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_result',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
